### ISSUE TITLE
Default options.include_files will cause subdirectories not being packaged

### ISSUE THREAD

**Issue by b4rd** [ttulka/grunt-aws-lambda-package#1]
The documentation states that omitting `include_files` has the same effect as specifying `**/*`, but it does not. It will skip files that reside in subdirctories.

Since I don't use .npmignore, I just specify `**/*` for now.

**Comment by ttulka** [comment]
I decided not to process the .npmignore file as the plugin is suppose to pack the deployment outcomes rather than development sources. The fix is released as 0.0.6 and should work as specified.
Thank you for the issue!

**Comment by b4rd** [comment]
Thank you for the quick reaction. :relaxed:
